/**
 * Phase 2G — weekly digest email.
 *
 * Replaces the Phase 1 one-email-per-prospect behaviour with a single weekly
 * email to the operator: a top section featuring prospects with a recommended action
 * (priority_score >= threshold, non-no_action) — each rendered with the full
 * Phase 1 per-prospect layout incl. the ready-to-send draft — followed by a
 * compact monitoring table for everyone else. Per-prospect detail also lives in
 * the dashboard (monitoring_results / Assessments tab).
 */
import type { AgentOutput } from "@/lib/llm/schema";
import type { AgentTouchpoint } from "@/lib/llm/aggregate";
import { renderProspectBriefingHtml } from "@/lib/email/render-briefing";

export type DigestEntry = {
  fullName: string;
  agentOutput: AgentOutput;
  recentTouchpoints: AgentTouchpoint[];
};

export function isActionable(entry: DigestEntry, alertThreshold: number): boolean {
  const t = entry.agentOutput.potential_touchpoint;
  return t.touchpoint_type !== "no_action" && t.priority_score >= alertThreshold;
}

export function buildDigestSubject(runDate: string, alertCount: number): string {
  return alertCount > 0
    ? `Donor Outreach Weekly Digest — ${runDate} (${alertCount} action${alertCount === 1 ? "" : "s"} recommended)`
    : `Donor Outreach Weekly Digest — ${runDate} (monitoring only)`;
}

export function renderDigestHtml(args: {
  entries: DigestEntry[];
  alertThreshold: number;
  runDate: string;
  generatedAt: Date;
}): string {
  const { entries, alertThreshold, runDate, generatedAt } = args;
  const featured = entries.filter((e) => isActionable(e, alertThreshold));
  const monitoring = entries.filter((e) => !isActionable(e, alertThreshold));

  const featuredHtml = featured
    .map(
      (e) => `
<section style="margin: 24px 0; padding-top: 8px; border-top: 3px solid #007acc;">
  <h2 style="margin-bottom: 4px;">⭐ ${escapeHtml(e.fullName)}</h2>
  ${renderProspectBriefingHtml({
    fullName: e.fullName,
    agentOutput: e.agentOutput,
    recentTouchpoints: e.recentTouchpoints,
    generatedAt,
  })}
</section>`
    )
    .join("");

  const monitoringRows = monitoring
    .map((e) => {
      const t = e.agentOutput.potential_touchpoint;
      const rs = e.agentOutput.relationship_state;
      return `
    <tr>
      <td>${escapeHtml(e.fullName)}</td>
      <td>${escapeHtml(titleCase(rs.stage))}</td>
      <td style="text-align:center;">${t.priority_score}/10</td>
      <td>${escapeHtml(e.agentOutput.monitoring_results.summary)}</td>
    </tr>`;
    })
    .join("");

  const monitoringHtml =
    monitoring.length > 0
      ? `
<h2 style="margin-top: 28px;">📋 Monitoring (no action recommended)</h2>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
  <thead style="background-color: #f5f5f5;">
    <tr><th>Prospect</th><th>Stage</th><th>Score</th><th>Summary</th></tr>
  </thead>
  <tbody>${monitoringRows}</tbody>
</table>`
      : "";

  return `
<h1>Donor Outreach — Weekly Digest</h1>
<p style="color:#555;">Week of ${escapeHtml(runDate)} · ${entries.length} prospect(s) assessed · ${featured.length} action(s) recommended.</p>
${featured.length > 0 ? `<h2 style="margin-top: 20px;">⭐ Recommended actions (${featured.length})</h2>` : "<p><em>No outreach recommended this week — monitoring only.</em></p>"}
${featuredHtml}
${monitoringHtml}
<hr style="margin: 24px 0;">
<p style="font-size: 12px; color: #666;">
  <em>Generated by the MAS Donor Intelligence System on ${generatedAt.toLocaleString()}. Per-prospect detail is in the dashboard (Assessments tab).</em>
</p>
`;
}

function titleCase(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function escapeHtml(s: string): string {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
