import type { AgentOutput } from "@/lib/llm/schema";
import type { AgentTouchpoint } from "@/lib/llm/aggregate";

export type RenderBriefingInput = {
  fullName: string;
  agentOutput: AgentOutput;
  recentTouchpoints: AgentTouchpoint[];
  generatedAt: Date;
};

/**
 * Phase 1 per-prospect HTML structure preserved verbatim from the n8n
 * "Format for Gmail" code node. Layout must match byte-for-byte (modulo
 * timestamp + agent text) so Phase 2C eval parity holds.
 */
export function renderProspectBriefingHtml(input: RenderBriefingInput): string {
  const { fullName, agentOutput, recentTouchpoints, generatedAt } = input;
  const summary = agentOutput.monitoring_results.summary;
  const alerts = agentOutput.monitoring_results.key_alerts;
  const touchpoint = agentOutput.potential_touchpoint;

  const sortedTouchpoints = recentTouchpoints
    .filter((tp) => tp.completedDate && tp.completedDate !== "")
    .sort(
      (a, b) =>
        new Date(b.completedDate).getTime() - new Date(a.completedDate).getTime()
    )
    .slice(0, 5);

  const recentEngagementHtml =
    sortedTouchpoints.length > 0
      ? `
<h3>📅 Recent Engagement</h3>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
  <thead style="background-color: #f5f5f5;">
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Summary</th>
      <th>Response</th>
    </tr>
  </thead>
  <tbody>
    ${sortedTouchpoints
      .map(
        (tp) => `
    <tr>
      <td>${escapeHtml(tp.completedDate)}</td>
      <td>${escapeHtml(titleCase(tp.touchpointType || "N/A"))}</td>
      <td>${escapeHtml(tp.summary || "N/A")}</td>
      <td>${escapeHtml(tp.response ? titleCase(tp.response) : "N/A")}</td>
    </tr>
    `
      )
      .join("")}
  </tbody>
</table>
`
      : "";

  void fullName;

  return `
<h2>Donor Monitoring Alert - Priority ${touchpoint.priority_score}/10</h2>

<h3>📊 Monitoring Summary</h3>
<p><strong>Overall Assessment:</strong> ${escapeHtml(summary)}</p>

<h3>🚨 Key Alerts Detected</h3>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
  <thead style="background-color: #f5f5f5;">
    <tr>
      <th>Source</th>
      <th>Headline</th>
      <th>Content Summary</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    ${alerts
      .map(
        (alert) => `
    <tr>
      <td>${escapeHtml(titleCase(alert.alert_source))}</td>
      <td><strong>${escapeHtml(alert.headline)}</strong></td>
      <td>${escapeHtml(alert.content_summary)}</td>
      <td><a href="${escapeAttr(alert.source_link)}" target="_blank">View</a></td>
    </tr>
    `
      )
      .join("")}
  </tbody>
</table>

${recentEngagementHtml}

<h3>💡 Engagement Recommendation</h3>
<ul>
  <li><strong>Touchpoint Type:</strong> ${escapeHtml(titleCase(touchpoint.touchpoint_type))}</li>
  <li><strong>Priority Score:</strong> ${touchpoint.priority_score}/10</li>
</ul>

<p><strong>Rationale:</strong> ${escapeHtml(touchpoint.engagement_rationale)}</p>

<h3>📧 Draft Outreach</h3>
<div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #007acc; margin: 15px 0;">
  <p style="font-family: Arial, sans-serif; margin: 0;">${escapeHtml(touchpoint.draft_content)}</p>
</div>

<hr style="margin: 20px 0;">
<p style="font-size: 12px; color: #666;">
  <em>Generated by MAS Donor Intelligence System on ${generatedAt.toLocaleString()}</em>
</p>
`;
}

function titleCase(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s).replace(/"/g, "&quot;");
}

export function buildBriefingSubject(fullName: string, priorityScore: number): string {
  return `🎯 High Priority Donor Alert: ${fullName} (Score: ${priorityScore}/10)`;
}
